# Generated by Django 4.2.16 on 2024-10-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
